language: ruby
branches:
  only:
    - master
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head