language: ruby
before_script:
  - bundle exec rake compile
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode